### PR TITLE
Fix no default export (closes #10)

### LINKED ISSUE #10: env script shouldn't use default export apparently
So this took me two days of scratching my head to find the root cause of this, but for some reason it seems the aot compiler silently chokes when using default exports - but only sometimes :'(.

https://github.com/captaincaius/rocketdefaultexporttestcase/pull/1/files#diff-5c26d2c8f8838f32ace87fdecd6344eaL26

It's really annoying cause if you look at the test case, the problem only shows up in certain unpredictable scenarios.

Anyway, it's a one-liner, but it would break existing projects :-/ ...

### PR DESCRIPTION
**Pull request by captaincaius**

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -139,7 +139,7 @@ class NgxScriptsCli {
         const s = v.replace(/'/g, "\\'").replace(/\\"/g, '"');
         return `'${s}'`;
       });
-      env = `export default ${env};\n`;
+      env = `export const env = <{ [s: string]: string; }>${env};\n`;
     }
```
Comment (captaincaius) [inline index.js]: in case this overexplicit ugliness makes you scratch your head...
It's a shutup for noImplicitAny for when any of the values are null.

Comment (sinedied) [reply index.js]: Why use a cast instead of an explicit type, ie: `export const env: { [s: string]: string; } = ${env};`?

Comment (captaincaius) [reply index.js]: Yeah agreed - I try to avoid type assertions whenever possible too.

Initially was gonna do this instead, but then I thought it might give me a "type undefined is not assignable to string" or whatever that way, but TBH I didn't try it, and typescript still surprises me sometimes :P
I'll give it a try today and let you know.

Comment (captaincaius) [reply index.js]: so I tried it and it does give that error, but only when strictNullChecks is enabled - which I think we don't have enabled by default.
But that's be easily avoided by adding a "| null" to the value type anyway.
I'll change it now :) good catch!

**Comment by sinedied** [comment]
👍
